version: '3.9'

services:
  remmina:
    container_name: remmina
    image: lscr.io/linuxserver/remmina:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuching
    volumes:
      - /data/remmina/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped